/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Modelo.Conexion;
import Modelo.Hash;
import Modelo.SQLUsuario;
import Modelo.Usuario;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class Frm_Registro extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Registro
     */
     public void loadTipo()
    {
        try
        {
            Conexion con = new Conexion();
            Connection cn = con.getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT id_tipo FROM tipo_usuario");
            JCmbTipo.removeAllItems();
            while(rs.next()){
                JCmbTipo.addItem(rs.getString(1));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }
    public Frm_Registro() {
        initComponents();
        loadTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelFrm = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        JLContra = new javax.swing.JLabel();
        JLUsuario = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        JLConCon = new javax.swing.JLabel();
        txtConfPass = new javax.swing.JPasswordField();
        JLNom = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        JLEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        JLTipo = new javax.swing.JLabel();
        JCmbTipo = new javax.swing.JComboBox<>();
        JBtnRegistro = new javax.swing.JButton();
        JBtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Usuarios");

        JPanelFrm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel", 1, 14))); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JLContra.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLContra.setText("Contraseña:");

        JLUsuario.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLUsuario.setText("Usuario:");

        txtPassword.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JLConCon.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLConCon.setText("Confirmar Contraseña:");

        txtConfPass.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JLNom.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLNom.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JLEmail.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLEmail.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JLTipo.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLTipo.setText("Tipo de Usuario:");

        JCmbTipo.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JBtnRegistro.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JBtnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Check_16x16.png"))); // NOI18N
        JBtnRegistro.setText("Registrar");
        JBtnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRegistroActionPerformed(evt);
            }
        });

        JBtnSalir.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cancel_16x16.png"))); // NOI18N
        JBtnSalir.setText("Salir");
        JBtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel1.setText("1. Administrador");

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel2.setText("2. Inventarios");

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jLabel3.setText("3. Usuario");

        javax.swing.GroupLayout JPanelFrmLayout = new javax.swing.GroupLayout(JPanelFrm);
        JPanelFrm.setLayout(JPanelFrmLayout);
        JPanelFrmLayout.setHorizontalGroup(
            JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelFrmLayout.createSequentialGroup()
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelFrmLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnSalir))
                    .addGroup(JPanelFrmLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelFrmLayout.createSequentialGroup()
                                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLConCon)
                                    .addComponent(JLUsuario)
                                    .addComponent(JLContra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtPassword)
                                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JPanelFrmLayout.createSequentialGroup()
                                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLNom)
                                    .addComponent(JLEmail)
                                    .addComponent(JLTipo))
                                .addGap(70, 70, 70)
                                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNombre)
                                    .addComponent(JCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))))
                .addGap(34, 34, 34))
        );
        JPanelFrmLayout.setVerticalGroup(
            JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelFrmLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLContra)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLConCon)
                    .addComponent(txtConfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNom)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(JPanelFrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelFrmLayout.createSequentialGroup()
                        .addComponent(JBtnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JBtnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelFrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelFrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBtnSalirActionPerformed
     private void limpiar() {
        txtUsuario.setText("");
        txtPassword.setText("");
        txtConfPass.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
    }
    private void JBtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRegistroActionPerformed
        SQLUsuario modSql = new SQLUsuario();
        Usuario mod = new Usuario();

        String pass = new String(txtPassword.getPassword());
        String passC = new String(txtConfPass.getPassword());

        if (txtUsuario.getText().equals("") || pass.equals("") || passC.equals("") || txtNombre.getText().equals("") || txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios, debe llenar todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            if (pass.equals(passC)) {

                if (modSql.existeUsuario(txtUsuario.getText()) == 0) {

                    if (modSql.esEmail(txtEmail.getText())) {

                        String nuevoPass = Hash.sha1(pass);

                        mod.setUsuario(txtUsuario.getText());
                        mod.setPassword(nuevoPass);
                        mod.setNombre(txtNombre.getText());
                        mod.setEmail(txtEmail.getText());
                        int idTipo=0;
                        idTipo = Integer.parseInt(JCmbTipo.getSelectedItem().toString());
                        mod.setId_Tipo(idTipo);

                        if (modSql.registrar(mod)) {
                            JOptionPane.showMessageDialog(null, "Registro Guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                            limpiar();
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al Guardar", "Error", JOptionPane.ERROR_MESSAGE);
                            limpiar();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El email es incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JBtnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnRegistro;
    private javax.swing.JButton JBtnSalir;
    private javax.swing.JComboBox<String> JCmbTipo;
    private javax.swing.JLabel JLConCon;
    private javax.swing.JLabel JLContra;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLNom;
    private javax.swing.JLabel JLTipo;
    private javax.swing.JLabel JLUsuario;
    private javax.swing.JPanel JPanelFrm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtConfPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
