/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Modelo.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author diego
 */
public class Frm_StockAlm extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_StockAlm
     */
    void loadAlmacenes()
    {
        try
        {
            Conexion con = new Conexion();
            Connection cn = con.getConexion();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nombre_almacen FROM almacen");
            JCmbAlmacen.removeAllItems();
            while(rs.next()){
                JCmbAlmacen.addItem(rs.getString(1));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    public Frm_StockAlm() {
        initComponents();
        loadAlmacenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLbl1 = new javax.swing.JLabel();
        JLbl2 = new javax.swing.JLabel();
        JCmbAlmacen = new javax.swing.JComboBox<>();
        JBtnStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTbStock = new javax.swing.JTable();
        btnPDF = new javax.swing.JButton();

        setClosable(true);
        setTitle("Stock por Almacen");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Script.png"))); // NOI18N

        JLbl1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        JLbl1.setText("Stock por Almacén");

        JLbl2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JLbl2.setText("Seleccionar Almacén:");

        JCmbAlmacen.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N

        JBtnStock.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        JBtnStock.setText("Ver Stock");
        JBtnStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnStockActionPerformed(evt);
            }
        });

        JTbStock.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        JTbStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Almacen", "Producto", "Stock Actual"
            }
        ));
        jScrollPane1.setViewportView(JTbStock);

        btnPDF.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        btnPDF.setText("Exportar a PDF");
        btnPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbl1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLbl2)
                    .addComponent(JCmbAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnStockActionPerformed
        try
        {
            Conexion con = new Conexion();
            Connection cn = con.getConexion();
            String sql="SELECT almacen.nombre_almacen, producto.codigo_producto, stock.stock_producto\n" +
            "FROM stock\n" +
            "INNER JOIN almacen ON almacen.id_almacen = stock.fk_almacen\n" +
            "INNER JOIN producto ON producto.codigo_producto = stock.fk_producto WHERE almacen.nombre_almacen=?";
            Object[] modelo = new Object[3];
            DefaultTableModel t_model = (DefaultTableModel) JTbStock.getModel();
            t_model.setRowCount(0);
            JTbStock.setModel(t_model);
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, JCmbAlmacen.getSelectedItem().toString());
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                modelo[0]=rs.getString("almacen.nombre_almacen");
                modelo[1]=rs.getString("producto.codigo_producto");
                modelo[2]=rs.getString("stock.stock_producto");
                t_model.addRow(modelo);
            }
            JTbStock.setModel(t_model);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_JBtnStockActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        String strNomAlmacen="";
        strNomAlmacen = JCmbAlmacen.getSelectedItem().toString();
        
        try {
            Conexion con = new Conexion();
            Connection cn = con.getConexion();
            JasperReport reporte = null;
            String ruta="Reportes/Stock_Almacen.jasper";
            Map parametros = new HashMap();
            
            parametros.put("value_almacen_nombre", strNomAlmacen);
            reporte = (JasperReport) JRLoader.loadObjectFromFile(ruta);
            JasperPrint print_Repo = JasperFillManager.fillReport(reporte, parametros, cn);
            JasperViewer vista_Repo = new JasperViewer(print_Repo, false);
            vista_Repo.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            vista_Repo.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Frm_StockP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnStock;
    private javax.swing.JComboBox<String> JCmbAlmacen;
    private javax.swing.JLabel JLbl1;
    private javax.swing.JLabel JLbl2;
    private javax.swing.JTable JTbStock;
    private javax.swing.JButton btnPDF;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
